apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:BEx/XQxuan9HN0FIK8CdABQ3qn3VSAhacmhou67ucGqsUL8DzJuVIQ/wb+QnmGTX0W9SJguIIMl3vTSjyxw7DVHUAs+6BB40IXlxL1yNpsAHZG4ZrwP2G+W+QdEFzzTg3OWv4eFCFbU0WbiDwO2YovPPssWuZxsqR76KQz1TAzmkLTXeuKT4ZN/3FunOApQNDYNed/fTCa/pIK0sJQ9+8Q1fJ9xfEozk4bCSMTSdN+VkaIGCttuev2WYWsnKcb3hecH+L3wL/z+neX50wlfEcNt1ugTxSchv2J6FQyOgg79qv+tlsyKHKUO/1NI=,iv:HAhv3gcA+J6g1JNwuIR/mfo183oRKtTNcwgzYbYRMtk=,tag:+20c8IQH06mmEKvU2aFS2w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1cyj5h2ztmp7faywmkkssnfxhsh6rfqt6zed0dqdeqw89gc0sygsqhnlamc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeFo5VjhEcTNEMXJnWXcv
            NmtHVndBaWh0Y3k4c3dtWXU5V0NOQjhnS0c0CmxjR3ZRRnl0MzZ5MmxsaU9zekYz
            bGdoZmJ3TzR3aHZwd0VhTERSYUpzeDAKLS0tIFVTRi91VlN4QVFKeURKcS9wZjFt
            S3FNM3F1ZHlMMnJQdjMraXUrQ0pqYmcK9ULMgSluVOBG9qCcfN5DI8M3ZOiQ52So
            adOHFV5P6d82L+l/4wLbmXx2o5zc7dpPwE7465aS87lsLe8Y9FC0wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-06T11:17:09Z"
    mac: ENC[AES256_GCM,data:NCMHXaIVoYeiSqpnGyCXgroU+EhDZx+7c7+7Xp3r1TdojcOyXceYvZSC9y7k2QYsXy/ziGRbA4JOJxPBsmvaiixb3Tl0EQ0p8bHVOe7KfmBLsTdRNm+AufsAy9anzaUCGZZ9NK/PV3k6Gym32nx7My5hVPumuNKq3Y+i3Gl1I8A=,iv:PD07V8BJUoekYBs98IkQf4K+rUiDyR7ydRuC1XBrsJ0=,tag:YtBrC/ak1Yr+HMEmK4HSyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.0
