apiVersion: helm.toolkit.fluxcd.io/v3
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "70.x"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    grafana:
      adminPassword: mischa
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grs.wvhomelab.xyz

        ## TLS configuration for grafana Ingress
        ## Secret must be manually created in the namespace
        ##
        tls:
          - secretName: linkding-tls-secret
            hosts:
              - lds.wvhomelab.xyz
